export const ACCEPTABLE_ORDER_CREATED_DATE_LEEWAY_SECONDS = 30;
export const ACCEPTABLE_TIME_TO_PAY_FOR_OPEN_ORDER_SECONDS = 30;
export const APPROVAL_WINDOW_SECONDS = 60;
export const MAX_OFFER_DELIVERY_ATTEMPTS = 3;
export const PAYMENT_WINDOW_SECONDS = 600;

// Task run intervals
export const OFFER_SYNC_TASK_RUN_INTERVAL_SECONDS = 30;
export const ORDER_APPROVAL_STATUS_TASK_RUN_INTERVAL_SECONDS = 10;
export const ORDER_FILL_STATUS_TASK_RUN_INTERVAL_SECONDS = 10;
export const ORDER_PAYMENT_STATUS_TASK_RUN_INTERVAL_SECONDS = 10;
export const RECEIVING_ACCOUNT_TRANSFER_TASK_RUN_INTERVAL_SECONDS = 5;
