export const ACCEPTABLE_ORDER_CREATED_DATE_LEEWAY_SECONDS = 30;
export const APPROVAL_WINDOW_SECONDS = 60;
export const MAX_PRODUCT_RECORD_DELIVERY_ATTEMPTS = 3;
export const PAYMENT_WINDOW_SECONDS = 600;

// Task run intervals
export const ORDER_APPROVAL_STATUS_TASK_RUN_INTERVAL_SECONDS = 10;
export const PRODUCT_RECORD_SYNC_TASK_RUN_INTERVAL_SECONDS = 10;
